# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/1dfastai',
                'doc_host': 'https://waterboy96.github.io',
                'git_url': 'https://github.com/waterboy96/1dfastai',
                'lib_path': '1dfastai'},
  'syms': {'1dfastai.core': {'1dfastai.core.foo': ('core.html#foo', '1dfastai/core.py')}}}
